import { ReactQueryProvider } from "@/providers/ReactQueryProvider";
import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import ProgressBarProvider from "@/providers/Progressbar";
import Navbar from "@/components/misc/Navbar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <ReactQueryProvider>
      <html lang="en">
        <body className={inter.className}>
          {children}
          <ProgressBarProvider />
        </body>
      </html>
    </ReactQueryProvider>
  );
}
